Itians/Itians/Controllers/AdminJobController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Itians.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Itians.Controllers
{
	[Authorize(Roles = "1")]
	public class AdminJobController : Controller
	{
		itiansContext db;
		public AdminJobController(itiansContext db)
		{
			this.db = db;
		}
		public IActionResult Index()
		{
			
			var Job = db.JobTypes.ToList();
			ViewBag.Job = Job;
			return View();
		}
		
		public IActionResult edit(int id)
		{
			JobType J = db.JobTypes.Where(n => n.JobTypeId == id).SingleOrDefault();
			return View(J);
		}
		
		[HttpPost]
		public IActionResult edit(JobType J)
		{
			db.Entry(J).State = EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");

		}
		
		public IActionResult add()
		{
			return View();
		}
		[HttpPost]
		
		public IActionResult add(JobType J)
		{
			db.JobTypes.Add(J);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		
		public IActionResult delete(int id)
		{
			JobType J = db.JobTypes.Where(o => o.JobTypeId == id).SingleOrDefault();
			db.Remove(J);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Itians/Itians/Views/AdminJob/Index.cshtml
@model JobModel
@{
    ViewData["Title"] = "Admin Control - Jobs";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

@section CSS{
    <link rel="stylesheet" href="~/Source/css/AdminStyle.css" />
}
<section class="Jobs-main">
    <div class="container">
        <div class="card ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminApproveUser">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminApproveCompany">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminRoll" tabindex="-1" aria-disabled="true">User Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminSkill" tabindex="-1" aria-disabled="true">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  active" aria-current="true" asp-action="Index" asp-controller="AdminJob" tabindex="-1" aria-disabled="true">Jobs</a>
                    </li>
                    
                </ul>
            </div>
            <div class="card-body job-body">
                <h3>Job Title</h3>
                <!-- add New job types -->
                <a class="btn btn-outline-primary" asp-action="add" asp-controller="AdminJob">Add New Job</a>

                <!-- Table of job types -->
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">job title</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                         
                        @foreach (var item in ViewBag.Job)
                        {
                            <tr>
                                <td>@item.JobType1</td>
                                <td>
                                    <a asp-action="edit" asp-controller="AdminJob" asp-route-id="@item.JobTypeId" class="link-admin"><i class="fas fa-pencil-alt"></i></a>
                                    <a asp-action="delete" asp-controller="AdminJob" asp-route-id="@item.JobTypeId" class="link-admin"><i class="fas fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

Itians/Itians/Views/AdminJob/add.cshtml
@model Itians.Models.JobType
@{
    ViewData["Title"] = "Control|Job";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

@section CSS{
    <link rel="stylesheet" href="~/Source/css/AdminStyle.css" />
}
<section class="Jobs-main align-content-center">
    <div class="container">
        <div class="card ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminApproveUser">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminApproveCompany">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminRoll" tabindex="-1" aria-disabled="true">User Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminSkill" tabindex="-1" aria-disabled="true">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="true " asp-action="Index" asp-controller="AdminJob" tabindex="-1" aria-disabled="true">Jobs</a>
                    </li>
                   
                </ul>
            </div>
            <div class="card-body job-body">

                <h3>Add Job</h3>
                <!--Edit JobType -->
                <form method="post">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th scope="row">
                                    <label asp-for="JobType1">Job:</label>
                                </th>
                                <td>
                                    <input type="text" class="skill-edit" asp-for="JobType1">
                                </td>

                            </tr>
                            <tr>
                                <th scope="row"><input type="Submit" class="btn btn-success" value="Add"></th>
                                <td>
                                    <a class="btn btndanger" asp-action="Index" asp-controller="AdminJob">Cancel</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Itians/Itians/Views/AdminJob/edit.cshtml
@model Itians.Models.JobType
@{
    ViewData["Title"] = "Control|Job";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
@section CSS{
    <link rel="stylesheet" href="~/Source/css/AdminStyle.css" />
}
<section class="Jobs-main align-content-center">
    <div class="container">
        <div class="card ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminApproveUser">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminApproveCompany">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminRoll" tabindex="-1" aria-disabled="true">User Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminSkill" tabindex="-1" aria-disabled="true">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="true" asp-action="Index" asp-controller="AdminJob" tabindex="-1" aria-disabled="true">Jobs</a>
                    </li>
                </ul>
            </div>
            <div class="card-body job-body">

                <h3>Edit Job</h3>
                <!--Edit job -->
                <form method="post">
                    <table class="table">
                        <tbody>
                            <tr hidden>
                                <th scope="row">
                                    <label asp-for="JobTypeId">Id:</label>
                                    <input  asp-for="JobTypeId" />
                                </th>
                            </tr>
                            <tr>
                                <th scope="row">
                                    <label asp-for="JobType1">Job Title:</label>
                                </th>
                                <td>
                                    <input type="text" class="job-edit" asp-for="JobType1">
                                    <span class="text-danger" asp-validation-for="JobType1"></span>
                                </td>

                            </tr>
                            <tr>
                                <th scope="row"><input type="Submit" class="btn btn-success" value="Save"></th>
                                <td>
                                    <a class="btn btn-danger" asp-action="Index" asp-controller="AdminJob">Cancel</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}