Itians/Itians/Controllers/AdminGroupController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Itians.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Itians.Controllers
{
	[Authorize(Roles = "1")]
	public class AdminGroupController : Controller
	{
		itiansContext db;
		public AdminGroupController(itiansContext db)
		{
			this.db = db;
		}
		public IActionResult Index()
		{
			var group = db.Groups.ToList();
			ViewBag.group = group;
			return View();
		}
		public IActionResult edit(int id)
		{
			Group G = db.Groups.Where(o => o.GroupId == id).SingleOrDefault();
			SelectList U = new SelectList(db.Users.ToList(), "UserId", "Username ");
			ViewBag.user = U;
			return View(G);
		}
		[HttpPost]
		public IActionResult edit(Group G)
		{
			db.Entry(G).State = EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");

		}
		public IActionResult add()
		{
				SelectList U = new SelectList(db.Users.ToList(), "UserId", "Username ");
				ViewBag.user = U;
			
			return View();
		}
		[HttpPost]
		public IActionResult add(Group G)
		{
			db.Entry(G).State = EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");

		}
	}
}

Itians/Itians/Views/AdminGroup/Index.cshtml
@{
    ViewData["Title"] = "Admin Control - Groups";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
@section CSS{
    <link rel="stylesheet" href="~/Source/css/AdminStyle.css" />
}
<div class="Jobs-main align-content-center">
    <div class="container">
        <div class="card ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminApproveUser" tabindex="-1" aria-disabled="true">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminApproveCompany" tabindex="-1" aria-disabled="true">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminRoll" tabindex="-1" aria-disabled="true">User Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminSkill" tabindex="-1" aria-disabled="true">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminJob" tabindex="-1" aria-disabled="true">Jobs</a>
                    </li>
                   
                </ul>
            </div>
            <div class="card-body job-body">
                <h3>Groups</h3>
                <!-- add New group -->
                <a class="btn-outline-primary p-1" href="AddGroup.html">Add New Group</a>
                <table class="table  ">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.Group)
                        {
                            <tr>
                                <th scope="row">@item.GroupName </th>
                                <td>
                                    <a asp-action="edit" asp-controller="AdminGroup" asp-route-id="@item.GroupId" class="link-admin"><i class="fas fa-pencil-alt"></i></a>
                                    <a asp-action="delete" asp-controller="AdminGroup" asp-route-id="@item.GroupId" class="link-admin"><i class="fas fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Itians/Itians/Views/AdminGroup/add.cshtml
@model Itians.Models.Group
@{
    ViewData["Title"] = "add";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
@section CSS{
    <link rel="stylesheet" href="~/Source/css/AdminStyle.css" />
}
<div class="Jobs-main align-content-center">
    <div class="container">
        <div class="card ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminApproveUser" tabindex="-1" aria-disabled="true">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminApproveCompany" tabindex="-1" aria-disabled="true">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminRoll" tabindex="-1" aria-disabled="true">User Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminSkill" tabindex="-1" aria-disabled="true">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminJob" tabindex="-1" aria-disabled="true">Jobs</a>
                    </li>
                </ul>
            </div>
            <div class="card-body job-body">
                <h3>Add Group</h3>
                <!--Add group -->
                <form method="post">
                    <table class="table">
                        <tbody>
                            <tr hidden>
                                <th scope="row">ID :</th>
                                <td><input type="text" asp-for="GroupId" /></td>
                            </tr>
                            <tr>
                                <th scope="row">Name : </th>
                                <td>
                                    <input type="text" asp-for="GroupName" />
                                </td>

                            </tr>
                            <tr>
                                <th scope="row">Description : </th>
                                <td>
                                    <textarea asp-for="GroupDesc" type="text" class="group-edit" cols="80" rows="5"></textarea>
                                </td>

                            </tr>
                            <tr>
                                <th scope="row"><label asp-for="GroupAdmins">Admin 1 : </label> </th>
                                <td>
                                    <select asp-for="GroupAdmins" asp-items="ViewBag.user"> </select>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row"><label asp-for="GroupAdmins">Admin 2 : </label> </th>
                                <td>
                                    <select asp-for="GroupAdmins" asp-items="ViewBag.user"> </select>
                                </td>

                            </tr>
                            <tr>
                                <th scope="row"><label asp-for="GroupAdmins">Admin 3 : </label> </th>
                                <td>
                                    <select asp-for="GroupAdmins" asp-items="ViewBag.user"> </select>
                                </td>

                            </tr>
                            <tr>
                                <th scope="row"><input type="Submit" class="btn btn-success" value="Save"></th>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </form>

            </div>
        </div>
    </div>
</div>

Itians/Itians/Views/AdminGroup/edit.cshtml
@model Itians.Models.Group
@{
    ViewData["Title"] = "edit";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
@section CSS{
    <link rel="stylesheet" href="~/Source/css/AdminStyle.css" />
}
<div class="Jobs-main align-content-center">
    <div class="container">
        <div class="card ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminApproveUser" tabindex="-1" aria-disabled="true">User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminApproveCompany" tabindex="-1" aria-disabled="true">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminRoll" tabindex="-1" aria-disabled="true">User Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminSkill" tabindex="-1" aria-disabled="true">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-action="Index" asp-controller="AdminJob" tabindex="-1" aria-disabled="true">Jobs</a>
                    </li>
                </ul>
            </div>
                <div class="card-body job-body">
                    <h3>Edit Group</h3>
                    <!--Edit group -->
                    <form method="post">
                        <table class="table">
                            <tbody>
                                <tr hidden>
                                    <th scope="row">ID :</th>
                                    <td><input readonly asp-for="GroupId" /></td>
                                </tr>
                                <tr>
                                    <th scope="row">Name : </th>
                                    <td>
                                        <input type="text" asp-for="GroupName" />
                                    </td>

                                </tr>
                                <tr>
                                    <th scope="row">Description : </th>
                                    <td>
                                        <textarea asp-for="GroupDesc" type="text" class="group-edit" cols="80" rows="5"></textarea>
                                    </td>

                                </tr>
                                <tr>
                                    <th scope="row"><label asp-for="GroupAdmins">Admin 1 : </label> </th>
                                    <td>
                                        <select asp-for="GroupAdmins" asp-items="ViewBag.user"> </select>                             
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row"><label asp-for="GroupAdmins">Admin 2 : </label> </th>
                                    <td>
                                        <select asp-for="GroupAdmins" asp-items="ViewBag.user"> </select>
                                    </td>

                                </tr>
                                <tr>
                                    <th scope="row"><label asp-for="GroupAdmins">Admin 3 : </label> </th>
                                    <td>
                                        <select asp-for="GroupAdmins" asp-items="ViewBag.user"> </select>
                                    </td>

                                </tr>
                                <tr>
                                    <th scope="row"><input type="Submit" class="btn btn-success" value="Save"></th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </form>

                </div>
            </div>
        </div>
    </div>