Itians/Itians/Controllers/EditCompanyController.cs
using Itians.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Itians.Models;
using Itians.Controllers.HelperClasses;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Itians.Controllers
{

    public class EditCompanyController : Controller
    {
        itiansContext db;
        IHostingEnvironment hostingEnvironment;
        public EditCompanyController(itiansContext db, IHostingEnvironment hostingEnvironment)
        {
            this.db = db;
            this.hostingEnvironment = hostingEnvironment;
        }
  
        public IActionResult ShowEditCompany()
        {
            Claim idClaim = User.Claims.SingleOrDefault(claim => claim.Type == ClaimTypes.NameIdentifier);
            int id = int.Parse(idClaim.Value);
            var company = db.Companies
                .Include(Company => Company.CompanyType)
                .FirstOrDefault(user => user.CompanyId == id);
         
            ViewBag.company = company;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SaveContact(EditCompany ReceivedCompany)
        {
            
                SaveFile("Cover", ReceivedCompany.Cover, ReceivedCompany.CompanyUsername, out string CoverFileName);
                SaveFile("Image", ReceivedCompany.Image, ReceivedCompany.CompanyUsername, out string ImageFileName);
                Company company = new Company
                {
                    CompanyId = ReceivedCompany.CompanyId,
                    Email = ReceivedCompany.Email,
                    WebsiteUrl = ReceivedCompany.WebsiteUrl,
                    Adress = ReceivedCompany.Adress,
                    Image = ReceivedCompany.Image == null ? ReceivedCompany.HiddenImage : ImageFileName,
                    Cover = ReceivedCompany.Cover == null ? ReceivedCompany.HiddenCover : CoverFileName
                };
                db.Entry(company).State = EntityState.Modified;
                db.Entry(company).Property(x => x.CompanyUsername).IsModified = false;
                db.Entry(company).Property(x => x.Description).IsModified = false;
                db.Entry(company).Property(x => x.EstablishDate).IsModified = false;
                db.Entry(company).Property(x => x.CompanyTypeId).IsModified = false;
                db.Entry(company).Property(x => x.License).IsModified = false;
                db.Entry(company).Property(x => x.Password).IsModified = false;
                db.Entry(company).Property(x => x.RoleId).IsModified = false;
                db.Entry(company).Property(x => x.IsApproved).IsModified = false;
                db.Entry(company).Property(x => x.CommentFromAdmin).IsModified = false;
            await db.SaveChangesAsync();
            return RedirectToAction("ShowEditCompany");
        }
        public async Task<IActionResult> SaveAboutUs(EditCompany ReceivedCompany)
        {
            if (ModelState.IsValid)
            {
                Company company = new Company
                {
                    CompanyId = ReceivedCompany.CompanyId,
                    Description=ReceivedCompany.Description,
                    EstablishDate=ReceivedCompany.EstablishDate
                };
                db.Entry(company).State = EntityState.Modified;
                db.Entry(company).Property(x => x.Adress).IsModified = false;
                db.Entry(company).Property(x => x.Image).IsModified = false;
                db.Entry(company).Property(x => x.Cover).IsModified = false;
                db.Entry(company).Property(x => x.CompanyUsername).IsModified = false;
                db.Entry(company).Property(x => x.Email).IsModified = false;
                db.Entry(company).Property(x => x.WebsiteUrl).IsModified = false;
                db.Entry(company).Property(x => x.CompanyTypeId).IsModified = false;
                db.Entry(company).Property(x => x.License).IsModified = false;
                db.Entry(company).Property(x => x.Password).IsModified = false;
                db.Entry(company).Property(x => x.RoleId).IsModified = false;
                db.Entry(company).Property(x => x.IsApproved).IsModified = false;
                db.Entry(company).Property(x => x.CommentFromAdmin).IsModified = false;
            }
            await db.SaveChangesAsync();
            return RedirectToAction("ShowEditCompany");
        }

        public void SaveFile(string file, IFormFile formFile, string username, out string filename)
        {
            if (formFile != null)
            {

                string uploadFile = Path.Combine(hostingEnvironment.WebRootPath, $"Attachments/{file}s");
                filename = username.Replace(".", "") + $"_{file}." + formFile.FileName.Split(".").Last();
                string filePath = Path.Combine(uploadFile, filename);
                formFile.CopyTo(new FileStream(filePath, FileMode.Create));
            }
            else
            {
                filename = "";
            }
        }

    }
}

Itians/Itians/Views/EditCompany/ShowEditCompany.cshtml
@model EditCompany
@{
    ViewData["Title"] = "EditCompany - "+ViewBag.company.CompanyUsername;
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<div class="container editProfile-page" id="forLanding">
    <div class="row">
        <div class="col-lg-4">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a class="nav-link link-primary" href="#contact-info">Contact Information</a>
                    </li>
                    <li class="list-group-item">
                        <a class="nav-link link-primary" href="#about-us">About Us</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card mb-3" id="contact-info">
                <form asp-action="SaveContact" asp-controller="EditCompany" method="POST" enctype="multipart/form-data">
                    <input type="hidden" asp-for="CompanyId" value="@ViewBag.company.CompanyId" />
                    <input type="hidden" asp-for="CompanyUsername" value="@ViewBag.company.CompanyUsername" />
                    <input type="hidden" asp-for="HiddenImage" value="@ViewBag.company.Image" />
                    <input type="hidden" asp-for="HiddenCover" value="@ViewBag.company.Cover" />

                    <div class="card-body">
                        <h5 class="card-title border-bottom">Contact Information</h5>
                        <div>
                            <div class="mb-3">
                                <label for="emailField" class="form-label">Email address</label>
                                <input type="email"
                                       class="form-control"
                                       id="emailField"
                                       placeholder="name@example.com"
                                       asp-for="Email" value=@ViewBag.company.Email />
                            </div>
                            <div class="mb-3">
                                <label for="webUrlField" class="form-label">Website Url</label>
                                <input type="text"
                                       class="form-control"
                                       id="webUrlField"
                                       placeholder="www.example.com"
                                       asp-for="WebsiteUrl" value=@ViewBag.company.WebsiteUrl />
                            </div>

                            <div class="mb-3">
                                <label for="addressField" class="form-label">Address</label>
                                <input type="text"
                                       class="form-control"
                                       id="addressField"
                                       placeholder="Egypt, Menofia, Shebin Alkom"
                                       asp-for="Adress" value=@ViewBag.company.Adress />
                            </div>
                            <div class="input-group mb-3">
                                <label class="input-group-text" for="profileFile">Profile Photo</label>
                                <input type="file" class="form-control" id="profileFile" name="Image" />
                            </div>
                            <div class="input-group mb-3">
                                <label class="input-group-text" for="coverFile">Profile Cover</label>
                                <input type="file" class="form-control" id="coverFile" name="Cover" />
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <div class="card mb-3" id="about-us">
                <form asp-action="SaveAboutUs" method="POST">
                    <input type="hidden" asp-for="CompanyId" value="@ViewBag.company.CompanyId" />
                    <div class="card-body">
                        <h5 class="card-title border-bottom">About Us</h5>
                        <div>
                            <div class="mb-3">
                                <textarea class="form-control" id="aboutMeField" name="Description">@ViewBag.company.Description</textarea>
                            </div>
                            <div class="mb-3">
                                <label for="establishField">Establish Data</label>
                                <input type="date"
                                       class="form-control"
                                       id="establishField" name="EstablishDate"
                                       value=@ViewBag.company.EstablishDate.ToString("yyyy-MM-dd") />
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" value="Save" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="goUp" id="goUp">
    <a href="#forLanding"><i class="fas fa-chevron-circle-up fa-3x"></i></a>
</div>